title: DoreTours (EECE 6356 Final Project)
sub_title: One Sentence Description
description: Paragraph or so Description
banner_image: doretours.png
focus_image: doretours.jpg
page_link: https://github.com/zappyfish/Dore-Tours/blob/master/Report.pdf
