title: Intellipill (2017 LinkedIn Bay Area Intern Hackathon Winner)
sub_title: An IoT solution to medication monitoring which provides relief for patients and caretakers.
description: we did a thing
banner_image: intellipill.jpeg
focus_image: intellipill.jpeg
page_link: https://www.linkedin.com/pulse/why-our-2017-linkedin-intern-hackathon-experience-emmeline-pelaez-kuo/
