title: DumbleDoor (2018 MakeHarvard 3rd Place Overall)
sub_title: One Sentence Description
description: Paragraph or so Description
banner_image: makeharvard.jpg
focus_image: makeharvard.png
page_link: https://devpost.com/software/dumbledoor
