title: OneHealth (2017 Microsoft Imagine Cup US Finalist & HackPrinceton 2nd Place Overall)
sub_title: One Sentence Descripti
description: onehealth stuff
banner_image: onehealth.png
focus_image: onehealth.png
page_link: https://imaginecup.microsoft.com/en-us/Team/0cb4e40e-b3d0-4b98-96eb-7ca7e11e4639
