title: trAIner (2018 Hack@CEWIT Best Data Visualization + Most Entrepreneurial Hack)
sub_title: One Sentence Description
description: Paragraph or so Description
banner_image: trainer.jpg
focus_image: trainer.png
page_link: Link to Website Page
