title: VADL 2018-2019 (NASA USLI 1st Place)
sub_title: 
description: Paragraph or so Description
banner_image: /assets/img/vadl.jpeg
focus_image: /assets/img/vadl.png
page_link: https://www.nasa.gov/marshall/news/news/releases/2019/19-018.html
