title: Vandy Vans (100+ Installs on Google Play)
sub_title: One Sentence Descriptio
description: Paragraph or so Description
banner_image: vandyvans.png
focus_image: vandyvans.png
page_link: https://play.google.com/store/apps/details?id=liamkengineering.vandyvans&hl=en_US
